[packages]

[packages.sisor_2025]

path = "https://raw.githubusercontent.com/splor-mg/dados-sisor-2025/main/datapackage.json"

[packages.sigplan_2025]

path = "https://raw.githubusercontent.com/splor-mg/dados-sigplan-planejamento-2025/main/datapackage.json"

[packages.aux_classificadores]

path = "https://raw.githubusercontent.com/splor-mg/dados-aux-classificadores/main/datapackage.json"
